version: '3.7'
services:
  postgres:
    restart: unless-stopped
    image: 'postgres:16'
    command: postgres -c max_connections=2000
    container_name: postgres16
    ports:
      - 5432:5432
    env_file:
      - ./postgres.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - ranasoftcraft-network

  calendar:
    restart: unless-stopped
    image: ranasoftcraft/calendar:prod
    container_name: calendar
    depends_on:
      - postgres
    ports:
      - 8080:8080
    env_file:
      - ./postgres.env
      - ./calendar.env
    healthcheck:
      test: "curl --fail --silent host.docker.internal:6001/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - ranasoftcraft-network
  ngx:
    restart: unless-stopped
    image: ranasoftcraft/ranasoftcraft.co.in-2:prod
    container_name: nginx
    ports:
      - 80:80
    networks:
      - ranasoftcraft-network
volumes:
  data: null
networks:
  ranasoftcraft-network:
    driver: bridge